### ISSUE TITLE
puppeteer / chrome not working on Raspberry Pi

### ISSUE THREAD

**Issue by rhl2401** [soeren-b-c/lectio-skema-til-.ics-kalender#10] opened 2020-01-16 20:43 UTC
Jeg får følgende output efter at have fulgt opsætningen. Jeg har skrevet skoleid, brugernavn og password i .env samt besøger på linket med skoleid og brugerid. I console får jeg følgende output:

`> node-lectio@1.2.0 start /home/pi/Documents/lectio-skema-til-.ics-kalender-master
> NODE_ENV=production node -r reify node-lectio.js

browserLogin(): Error: Failed to launch chrome!
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 1: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome:ELF: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 1: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: ZP�t��: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 1: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �
@8
  @,*@@@h�������: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 11: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: g: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 12: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: o: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 13: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: u: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 14: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: }: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 15: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 16: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 17: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 18: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 19: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 20: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 21: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: �: not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 22: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: : not found
/home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: 23: /home/pi/Documents/lectio-skema-til-.ics-kalender-master/node_modules/puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: Syntax error: word unexpected (expecting ")")

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
fetch(): TypeError: Cannot destructure property `browser` of 'undefined' or 'null'.PuTTYCannot read property 'parent' of undefined
browserLogin(): Error: Failed to launch chrome!

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
fetch(): TypeError: Cannot destructure property `browser` of 'undefined' or 'null'.Cannot read property 'parent' of undefined
`

Jeg får følgende i browseren: 
`BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//skema.click//Lectio//DA
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-PUBLISHED-TTL:PT15M
X-WR-CALNAME:Lectio skema
X-WR-TIMEZONE:Europe/Copenhagen
END:VCALENDAR`

Altså starten af .ics er lavet korrekt, men modulerne kommer ikke med i outputtet.

**Comment by soeren-b-c** [comment] 2020-01-17 07:58
Hej Rasmus

Det ser ud til at der er noget der ikke virker ved din puppeteer / chrome.

Jeg har ikke lige en fungerende Pi ved hånden, så jeg kan ikke teste, men måske du kan forsøge at installere de pakker der bliver nævnt her:

https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

Det er en lang liste, og lidt at skyde med spredehagl, men i første omgang tænker jeg du bare gerne vil have det til at virke? :)

Hvis det virker kan en af os efterfølgende (hvis vi har tid /lyst) forsøge at finde ud af om alle pakkerne er nødvendige.

Mvh.
Søren

**Comment by rhl2401** [comment] 2020-01-17 08:38
Hej. Tusind tak for svar. 
Jeg har installeret alle pakkerne på RPI'en, jeg forsøger at sætte det op med, men det afhjalp intet .... Jeg vil meget gerne bidrage til at få det til at virke med hvad jeg kan 😄

**Comment by soeren-b-c** [comment] 2020-01-17 08:59
Det ser ud til at chrome som installeres vha. puppeteer ikke fungerer med Raspberry Pi'ens arkitektur...
Se evt.:
https://github.com/puppeteer/puppeteer/issues/550

Nederst i tråden lyder det til at en løsning kan være at installere chrome gennem apt eller en ppa, og så rette koden til, så den åbner den chrome som er installeret på computeren.

https://github.com/puppeteer/puppeteer/issues/550#issuecomment-562750404

Det er i filen `browser.js` linje 37 du skal fortælle den hvor den skal finde chrome.

Håber det giver mening - og at det virker!

**Comment by rhl2401** [comment] 2020-01-17 09:00
Perfekt. Jeg kigger på det i aften og vender tilbage!

**Comment by soeren-b-c** [comment] 2022-12-18 07:01
Duplicate of #24

**Closed as completed** 2022-12-19 19:46 UTC
